# Generated by Django 3.2 on 2023-03-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_domain', models.CharField(db_index=True, error_messages={'unique': 'This Subdomain already exists.'}, max_length=200, unique=True)),
                ('log', models.TextField(default='nothing', max_length=10000)),
                ('status', models.CharField(default='nothing', max_length=200)),
                ('port', models.IntegerField(default=8100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subdomain',
                'verbose_name_plural': 'subdomains',
                'ordering': ('sub_domain',),
            },
        ),
    ]
